// apps/angular-demo/src/app/input-component/input-component.component.ts
import { Component } from '@angular/core';
import { format } from "date-fns";
import {NgForm} from '@angular/forms';

export class Book{
    title: string
    constructor(title: string) {
      this.title = title;
    }
}

@Component({
  selector: 'abgov-input-component',
  templateUrl: './input-component.component.html',
  styleUrls: ['./input-component.component.css']
})
export class InputComponentComponent {
  constructor() { }

  book: Book=new Book("");
  name = '';
  date = new Date();
  formatDate = format(this.date, "yyyy-MM-dd");
  time = format(this.date, "HH:mm:ss");
  dateTime = format(this.date, "yyyy-MM-dd HH:mm")
  minDate = format(this.date, "yyyy-MM-dd");
  maxDate = format(this.getDateWithMonthOffset(1), "yyyy-MM-dd");

  // foobinding = new FormControl('');

  getDateWithMonthOffset(offset: number) {
    const d = new Date();
    d.setMonth(d.getMonth() + offset);
    return d;
  }

  onInputChangeEvent(event: any) {
    console.log('onEvent', event.detail);
  }

  handleTrailingIconClick() {
    console.log('handleTrailingIconClick');
  }

  onSubmit(f: NgForm) {
    console.log(f.value);  // { first: '', last: '' }
    console.log(f.valid);  // false
  }
}

<h1>Input</h1>

<h2>Basic</h2>

<goa-input
  id="foo"
  name="foo"
  (_change)="onInputChangeEvent($event)"
></goa-input>

<h2>Basic</h2>
<form #f="ngForm" (ngSubmit)="onSubmit(f)" novalidate>
  <input name="title" [(ngModel)]="book.title" />
  <goa-input name="title" [(ngModel)]="book.title"></goa-input>
  <button type="submit">Submit</button>
</form>

<p>Form value: {{ book.title }}</p>

<h2>Icons</h2>
<goa-input name="foo" leadingicon="finger-print"></goa-input>
<goa-input name="foo" trailingicon="finger-print"></goa-input>

<h2>Number</h2>
<goa-input name="foo" type="number" min="0" max="10" step="2"></goa-input>
<goa-input name="foo" type="number"></goa-input>

<h2>Date and time</h2>
<goa-input name="foo" type="date" [value]="formatDate"></goa-input>
<goa-input name="datetime" type="datetime-local" [value]="dateTime"></goa-input>
<goa-input name="time" type="time" [value]="time" step="1"></goa-input>

<goa-input type="date" name="Date with min max" [value]="formatDate" [min]="minDate" [max]="maxDate"></goa-input>

<h2>Icon Buttons</h2>
<goa-input
  name="foo"
  trailingicon="finger-print"
  handletrailingiconclick="true"
  (_trailingIconClick)="handleTrailingIconClick()"
  (_change)="onInputChangeEvent($event)"
></goa-input>

<h2>Disabled</h2>
<goa-input name="foo" disabled="true" placeholder="Find by name"></goa-input>

<h2>Error state</h2>
<goa-input name="foo" error></goa-input>

<h2>Focus</h2>
<goa-input name="foo"></goa-input>

<h2>Character count</h2>
<goa-input name="firstname" showcounter="true"></goa-input>

<h2>Character count with limit</h2>
<goa-input name="firstname" showcounter="true" maxcharcount="20"></goa-input>

// apps/react-demo/src/routes/input.tsx
import { GoAInput, GoAInputDate, GoAInputDateTime, GoAInputNumber, GoAInputTime } from '@abgov/react-components';
import { format } from 'date-fns';
import * as React from 'react';

export default function Input() {

  function noop(...args: unknown[]) {
    console.log(args)
  }

  const date = new Date();
  const minDate = new Date();
  const maxDate = new Date();
  maxDate.setFullYear(maxDate.getFullYear() + 1);

  return (
    <>
      <h1>Input</h1>
      <h2>Basic</h2>
      <GoAInput
        name=""
        value=""
        type="text"
        onChange={noop}
      />
      <GoAInputNumber
        name=""
        placeholder="Number"
        value={0}
        min={0}
        max={10}
        step={2}
        onChange={noop}
      />
      <GoAInputDate
        name="Date from string value"
        value={date.toISOString()}
        onChange={noop}
      />
      <GoAInputDate
        name="Date"
        value={date}
        onChange={noop}
      />
      <GoAInputDateTime
        name="Date Time"
        value={date}
        onChange={noop}
      />

      Time from Date value
      <GoAInputTime
        name="Time from date value"
        value={date}
        onChange={noop}
      />

      Time from string datetime ISO 8601 value
      <GoAInputTime
        name="Time w/ string datetime ISO 8601 value"
        value={date.toISOString()}
        onChange={noop}
      />

      Time from string mm:ss value
      <GoAInputTime
        name="Time from string mm:ss value"
        value={format(date, "hh:mm")}
        onChange={noop}
        step={1}
      />

      Time with a min and max 
      <GoAInputDate
        name="Date with min max"
        value={date.toISOString()}
        min={minDate.toISOString()}
        max={maxDate.toISOString()}
        onChange={noop}
      />

      <h2>Icons</h2>
      <GoAInput
        name=""
        value=""
        onChange={noop}
        type="text"
        leadingIcon="finger-print"
      />

      <GoAInput
        name=""
        value=""
        onChange={noop}
        type="text"
        trailingIcon="finger-print"
      />

      <h2>Icon Buttons</h2>
      <GoAInput
        trailingIcon="finger-print"
        name=""
        value=""
        onChange={noop}
        type="text"
        onTrailingIconClick={noop}
      />

      <h2>Disabled</h2>
      <GoAInput
        name=""
        value=""
        onChange={noop}
        type="text"
        disabled={true} 
        placeholder="Find by name"
      />

      <h2>Error state</h2>
      <GoAInput
        name=""
        value=""
        onChange={noop}
        type="text"
        error={true}
      />

      <h2>Focus</h2>
      <GoAInput
        name=""
        value=""
        onChange={noop}
        type="text"
      />

      <h2>Character count</h2>
      <GoAInput
        name="firstname"
        value=""
        onChange={noop}
        type="text"
        maxCharCount={20}
      />

      <h2>Character count with limit</h2>
      <GoAInput
        name="firstname"
        value=""
        onChange={noop}
        type="text"
        showCounter={true}
        maxCharCount={20}
      />

      <h2>Prefix and Suffix</h2>
    </>
  );
}
